### ISSUE TITLE
Add middlewares for post methods

### ISSUE THREAD

**Issue by kressha** [ccapdev1920T2/s11g11#2]
do form validation for add, drop, and swap classes and include middlewares in login and register

**Comment by kressha** [comment]
commit acaddbb874149b7b5e62478223842854b6ef1150 contains fixes in middlewares as they are now integrated in the MVC architecture. note that changes in the views and controller has been made in this branch, therefore must be merged into the master branch for changes to take effect as well.

**Comment by mk-mnzno** [comment]
hoki na bie
