### ISSUE TITLE
Fix registration validations and interface

### ISSUE THREAD

**Issue by mk-mnzno** [ccapdev1920T2/s11g11#3]
- [x] In the registration feature, the web application should have a client-side and server-side validation. The web application should not accept invalid ID numbers, thus, the web application should check if the ID number conforms to the standards of a DLSU ID number.

- [x] In the registration feature, if the user submitted an non-DLSU email, the web application should redirect the user back to the registration form then display the error there, not in a blank page. It would also be best to have a client-side validation for this, which does not allow the user to submit the form if the user enters a non-DLSU email.

- [x] In the registration feature, the College field is best represented as a drop down menu, since the number of colleges in the university is relatively few. Okay lang yung text field for the degree program, especially na hindi naman natin alam lahat ng programs ng university.

- [x] In the registration feature, the web application allows the user to register the same ID number twice. Per university guidelines, ID numbers are unique for each student. This should also be implemented in this web application.

**Comment by kressha** [comment]
Registration client-side and server-side validations are complete as of commit c083cc01a1abeb8a64799db5c8b1e24830b1fc3a. Also converted the College field into a dropdown selection in commit 331b4b53e04ec909da2c2e03058ddc318cf1eee7.

will do more testing later on. this issue will be closed in the meantime. any bugs will be opened as separate issues. 😎🥳
