### ISSUE TITLE
Add class feature error handling and AJAX

### ISSUE THREAD

**Issue by mk-mnzno** [ccapdev1920T2/s11g11#4]
- [x]  Errors in the add class feature, such as "401 Unauthorized error, schedules overlap" or "401 Unauthorized error, class already exists in class list" should be properly displayed to the user.

- [x]  It would be better if the add class feature adds classes to "My Classes" asynchronously without refreshing the page, using AJAX.

**Comment by mk-mnzno** [comment]
Commit 885aae29fcf83ab12aa8a0f6c11cb42444d97457 modifies and fixes all error handling to be done through AJAX, as well as normal case being handled similarly.

**Comment by kaylalatorre** [comment]
may bug po: missing checking for already existing courseCode ! will fix !

**Comment by kaylalatorre** [comment]
fixed na po BOSS
