### ISSUE TITLE
Drop class feature error handling and interface

### ISSUE THREAD

**Issue by mk-mnzno** [ccapdev1920T2/s11g11#6]
- [x]  In the drop classes feature, error messages should be properly displayed to the user. 

- [x]  In the drop classes feature, for a better user experience, it would be better if the user will just click an 'X' button beside the row of the classes which he wishes to remove, instead of typing the class number. This will lessen the number of errors that you need to check.

**Comment by kaylalatorre** [comment]
fixed na hihi

**Comment by kaylalatorre** [comment]
will fix button visuals XD
